_wandb:
    value:
        cli_version: 0.25.0
        e:
            ej40s3eapjyfuyd3ccm4hc6wclah2p61:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "981230305280"
                        used: "622009069568"
                email: saivijaay.vk@blackstraw.ai
                executable: /home/saivijaay.vk/CV/.venv/bin/python
                git:
                    commit: 9875c7d16975295546e8f2c48cae32b89a4dcda5
                    remote: https://github.com/RizwanMunawar/yolov7-segmentation.git
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-841091b0-aba7-7934-6807-80446fda7d4f
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-07ece9b3-4fbc-06de-5de5-10e31b2978f9
                host: antpc
                memory:
                    total: "134738522112"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/saivijaay.vk/CV/yolov7-segmentation/train.py
                python: CPython 3.10.12
                root: /home/saivijaay.vk/CV/yolov7-segmentation
                startedAt: "2026-03-08T11:19:57.210504Z"
                writerId: ej40s3eapjyfuyd3ccm4hc6wclah2p61
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 49
                - 80
                - 105
            "3":
                - 16
            "4": 3.10.12
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
artifact_alias:
    value: latest
batch_size:
    value: 4
bbox_interval:
    value: -1
bucket:
    value: ""
cache:
    value: null
cfg:
    value: /home/saivijaay.vk/CV/yolov7-seg/cfg/yolov7-seg.yaml
cos_lr:
    value: false
data:
    value: /home/saivijaay.vk/CV/yolov7-seg/seg/data/custom-seg.yaml
data_dict:
    value:
        names:
            "0": cluster_product
            "1": product
            "2": empty
        nc: 3
        train: /home/saivijaay.vk/CV/SEGMENTATION/Data_new/train
        val: /home/saivijaay.vk/CV/SEGMENTATION/Data_new/val
device:
    value: "0"
entity:
    value: null
epochs:
    value: 250
evolve:
    value: null
exist_ok:
    value: false
freeze:
    value:
        - 0
        - 1
        - 2
        - 3
hyp:
    value:
        anchor_t: 4
        box: 0.05
        cls: 4
        cls_pw: 1
        copy_paste: 0
        degrees: 0
        fl_gamma: 1.5
        fliplr: 0.5
        flipud: 0
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        iou_t: 0.2
        loss_ota: 1
        lr0: 0.0001
        lrf: 0.01
        mixup: 0.3
        momentum: 0.937
        mosaic: 0.5
        obj: 0.8
        obj_pw: 1
        paste_in: 0
        perspective: 0
        scale: 0.3
        shear: 0
        translate: 0.1
        warmup_bias_lr: 0.1
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.001
image_weights:
    value: false
imgsz:
    value: 768
label_smoothing:
    value: 0.01
local_rank:
    value: -1
multi_scale:
    value: false
name:
    value: exp
noautoanchor:
    value: false
noplots:
    value: false
nosave:
    value: false
noval:
    value: false
optimizer:
    value: AdamW
patience:
    value: 25
project:
    value: /home/saivijaay.vk/CV/SEGMENTATION/Predictions/
quad:
    value: false
rect:
    value: false
resume:
    value: false
save_dir:
    value: /home/saivijaay.vk/CV/SEGMENTATION/Predictions/exp
save_period:
    value: -1
seed:
    value: 0
single_cls:
    value: false
sync_bn:
    value: false
upload_dataset:
    value: false
weights:
    value: /home/saivijaay.vk/CV/yolov7-seg/weights/yolov7-seg.pt
workers:
    value: 8
